export default {
  'nav.home': 'الرئيسية', 'nav.series': 'المسلسلات', 'nav.movies': 'الأفلام', 'nav.new': 'الجديد', 'nav.myList': 'قائمتي', 'nav.search': 'بحث', 'nav.notifications': 'الإشعارات', 'nav.profile': 'الملف الشخصي', 'nav.menu': 'القائمة', 'nav.operations': 'العمليات', 'nav.settings': 'التفضيلات',
  'common.demo': 'تجريبي', 'common.academic': 'نموذج أكاديمي', 'common.simulation': 'محاكاة أكاديمية', 'common.todo': 'جاهز للتنفيذ اليدوي من قبل الطالب.', 'common.close': 'إغلاق', 'common.save': 'حفظ التفضيلات', 'common.saved': 'تم حفظ التغييرات محلياً.', 'common.storageError': 'التخزين غير متاح. تسري التغييرات لهذه الجلسة.', 'common.retry': 'إعادة المحاولة', 'common.back': 'العودة إلى الرئيسية', 'common.details': 'التفاصيل', 'common.all': 'الكل', 'common.viewAll': 'عرض الكل', 'common.configure': 'إعداد', 'common.loading': 'جارٍ تحميل الواجهة…', 'common.offline': 'لا يوجد اتصال. البيانات التجريبية المحلية متاحة.', 'common.error': 'تعذر تحميل الواجهة. حاول مجدداً.', 'common.skip': 'انتقل إلى المحتوى', 'common.docs': 'الدليل التقني', 'common.notOfficial': 'نموذج مستقل · ليس منتجاً رسمياً من Netflix', 'common.noResults': 'لا توجد عناوين تجريبية تطابق البحث.',
  'hero.eyebrow': 'البث · التوطين · العمليات', 'hero.title': 'فصلك القادم يبدأ هنا.', 'hero.description': 'استكشف واجهة بث جاهزة لمشروعك. جميع العناوين والملفات والمقاييس أمثلة تجريبية.', 'hero.explore': 'استكشاف الكتالوج التجريبي', 'hero.secondary': 'عن النموذج', 'hero.art': 'رسم تجريبي باستخدام CSS · بدون كتالوج مرخص', 'hero.edition': 'الأساس التقني / 01',
  'home.catalog': 'اكتشف الكتالوج', 'home.continue': 'متابعة المشاهدة', 'home.trending': 'الاتجاهات الإقليمية', 'home.recommendations': 'لجلستك القادمة', 'home.documentaries': 'وثائقيات', 'home.new': 'الجديد في العرض التجريبي', 'home.myListEmpty': 'قائمتك فارغة. أضف بطاقة لتجربة التخزين المحلي.', 'home.recommendationsTodo': 'عقد التوصيات جاهز. يجب على الطالب تنفيذ الخوارزمية وتبريرها يدوياً.', 'home.searchHint': 'البحث في العناوين التجريبية…', 'home.searchStatus': '{count} نتائج تجريبية', 'home.foundation': 'أساس لأفكارك', 'home.foundationBody': 'مكونات مستقلة ولغة ومنطقة منفصلتان وواجهة عمليات قابلة للتوسعة.',
  'title.name': 'عنوان تجريبي {number}', 'title.series': 'مسلسل', 'title.movies': 'فيلم', 'title.documentaries': 'وثائقي', 'title.play': 'فتح المشغل', 'title.add': 'إضافة إلى قائمتي', 'title.remove': 'إزالة من قائمتي', 'title.added': 'تمت الإضافة إلى القائمة التجريبية.', 'title.removed': 'تمت الإزالة من القائمة التجريبية.', 'title.description': 'بطاقة تجريبية. استبدل البيانات والرسم يدوياً بموارد معتمدة.', 'title.progress': '{progress}% · تقدم تجريبي',
  'settings.title': 'اجعله مناسباً لك', 'settings.subtitle': 'اللغة والمنطقة تفضيلات مستقلة.', 'settings.language': 'لغة الواجهة', 'settings.region': 'المنطقة', 'settings.audio': 'الصوت المفضل', 'settings.subtitles': 'الترجمة', 'settings.autoplay': 'تشغيل تلقائي (عقد)', 'settings.quality': 'الجودة المفضلة', 'settings.accessibility': 'إمكانية الوصول', 'settings.notifications': 'تفعيل الإشعارات التجريبية', 'settings.reduced': 'تقليل الحركة', 'settings.off': 'إيقاف', 'settings.availability': 'توفر تجريبي للمنطقة واللغة', 'settings.partial': 'توفر جزئي. قد لا تدعم بعض الأمثلة الصوت أو الترجمة باللغة المحددة.', 'settings.unavailable': 'لا توجد أمثلة محتوى لهذه المجموعة. لغة الواجهة تبقى متاحة.', 'settings.supported': 'هذه المجموعة مدعومة في البيانات التجريبية.', 'settings.translationPartial': 'هذا القاموس جزئي. تظهر النصوص الناقصة باللغة الإنجليزية.', 'settings.matrixNote': 'هذه المصفوفة مثال للواجهة وليست سياسة ترخيص أو توفر حقيقية.', 'settings.direction': 'اتجاه القراءة: {direction}',
  'account.title': 'حسابك', 'account.subtitle': 'بيانات وهمية فقط. بدون مصادقة أو معالجة مدفوعات.', 'account.summary': 'الملخص', 'account.subscription': 'الاشتراك', 'account.demoPlan': 'خطة تجريبية', 'account.payment': 'طرق الدفع', 'account.paymentEmpty': 'لا توجد طرق دفع. لا تدخل بيانات مصرفية حقيقية.', 'account.devices': 'الأجهزة', 'account.deviceDemo': 'متصفح محلي · جهاز تجريبي', 'account.profiles': 'الملفات الشخصية', 'account.preferences': 'التفضيلات', 'account.security': 'الأمان', 'account.securityTodo': 'عقود المصادقة والجلسات تنتظر التنفيذ اليدوي.', 'account.logout': 'إنهاء الجلسة التجريبية', 'account.logoutDemo': 'لا توجد جلسة مصادقة في هذا النموذج.',
  'notification.content': 'المحتوى', 'notification.account': 'الحساب', 'notification.security': 'الأمان', 'notification.billing': 'الفوترة', 'notification.devices': 'الأجهزة', 'notification.system': 'النظام', 'notification.placeholder': 'فئة تجريبية. اربط الأحداث المعتمدة يدوياً.', 'notification.empty': 'الإشعارات التجريبية معطلة في التفضيلات.',
  'player.title': 'مساحة التشغيل', 'player.subtitle': 'عناصر مرئية والتحقق من المدخلات. لا يوجد محرك بث متصل.', 'player.noMedia': 'لم يتم إعداد مصدر وسائط', 'player.sourceTodo': 'مهمة: ربط مصدر وسائط محلي معتمد يدوياً.', 'player.play': 'تشغيل', 'player.pause': 'إيقاف مؤقت', 'player.progress': 'تقدم التشغيل', 'player.volume': 'مستوى الصوت', 'player.audio': 'الصوت', 'player.subtitles': 'الترجمة', 'player.quality': 'الجودة', 'player.cast': 'البث إلى جهاز', 'player.settings': 'إعدادات المشغل', 'player.fullscreen': 'ملء الشاشة', 'player.next': 'الحلقة التالية', 'player.network': 'معاينة مدخلات الشبكة · محاكاة', 'player.bandwidth': 'نطاق تجريبي (Mbps)', 'player.preview': 'التحقق من مدخلات المحاكاة', 'player.previewResult': 'محاكاة: {mbps} Mbps · الجودة المطلوبة {quality}. لم يتم قياس النطاق.', 'player.unconnected': 'لا توجد وسائط أو خدمة متصلة بهذا العنصر. أكمل العقد يدوياً.', 'player.invalid': 'أدخل رقماً بين 0 و100.', 'player.nextTodo': 'التنقل بين الحلقات ينتظر عقداً يحدده الطالب.',
  'operations.title': 'مركز العمليات', 'operations.subtitle': 'بيانات محاكاة لأغراض أكاديمية. بدون أنظمة إنتاج متصلة.', 'operations.services': 'أمثلة الخدمات', 'operations.latency': 'زمن الاستجابة', 'operations.streams': 'البث المتزامن', 'operations.instances': 'النسخ', 'operations.cpu': 'المعالج', 'operations.charts': 'عينة زمن الاستجابة', 'operations.chartLabel': 'زمن استجابة تجريبي (ms)', 'operations.map': 'خريطة الأمثلة الإقليمية', 'operations.mapDisclaimer': 'مقاييس محاكاة', 'operations.events': 'ناقل الأحداث المرئي', 'operations.incidents': 'عقد الحوادث', 'operations.incidentTodo': 'مهمة: تعريف شدة الحوادث والاستجابة والتعافي يدوياً.', 'operations.autoscaling': 'محاكاة التوسع الأفقي', 'operations.scalingTodo': 'واجهة حالات فقط. مهمة: تعريف سياسة التوسع المعتمدة يدوياً.', 'operations.advance': 'تقديم حالة الخدمة التجريبية', 'operations.service': 'الخدمة', 'operations.append': 'إضافة عينة تجريبية', 'operations.scaling': 'حالة المعاينة', 'operations.mapKeyboard': 'بديل لوحة المفاتيح: اختر منطقة لقراءة المثال التجريبي.', 'operations.noFixture': 'لا توجد مقاييس تجريبية لهذه المنطقة.', 'operations.availability': 'التوفر',
  'state.loading': 'جارٍ التحميل', 'state.ready': 'جاهز', 'state.empty': 'فارغ', 'state.warning': 'تحذير', 'state.error': 'خطأ', 'state.offline': 'غير متصل', 'state.retrying': 'إعادة المحاولة', 'state.success': 'نجاح',
};
